name: lys-bbb
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ants=2.6.5
  - matplotlib
  - nibabel
  - numpy
  - pyside6
  - pytorch
  - scipy
  - simpleitk
  - pytest
  - ruff
  - pip
  - pip:
      - brkraw==0.5.7
      - -e .
