name: lys-irm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - nibabel
  - numpy<2.4
  - pyside6
  - pytorch
  - scipy=1.15.2
  - simpleitk
  - pytest
  - ruff
  - pip
  - pip:
      - antspyx==0.6.3
      - brkraw==0.5.7
      - -e .
